---
- hosts: k3s_cluster
  gather_facts: true
  become: true

  roles:
    - geerlingguy.pip
    - ansible-role-unix-tools
    #- ansible-role-prepare-nodes
    - ansible-role-download-k3s

- hosts: master
  become: true
  roles:
    - ansible-role-setup-k3s/master

- hosts: node
  become: true
  roles:
    - ansible-role-setup-k3s/agents
...