---
ansible_host: 127.0.0.1
ansible_user: vagrant
k3s_version: v1.22.3+k3s1
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
...